# blog_app/models.py
# REPLACE the old content with this

from sqlalchemy import Column, Integer, String, Text, DateTime, func
from ..services.database import Base

class GeneratedLawBlog(Base):
    """
    This model represents an AI-generated law blog post cached in the database.
    """
    __tablename__ = "generated_law_blogs"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Stores the user's original search query (e.g., "bail laws in India")
    # This is crucial for retrieving cached results.
    search_topic = Column(String(255), nullable=False, index=True)
    
    # The specific title of the generated blog post
    title = Column(String(500), nullable=False, unique=True)
    
    # The full Markdown content of the blog generated by the AI
    content = Column(Text, nullable=False)
    
    # The timestamp of when the blog was generated and cached
    createdAt = Column(DateTime(timezone=True), server_default=func.now())